**Udo Mary Imeabasi, WTF/2025/3304, udomary963@outlook.com**

In [49]:
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
%matplotlib inline
from google.colab import drive
drive.mount('/content/drive')
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In exercise folder hiring.csv.

The data contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary.

Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates.


Using this predict salaries for following candidates,
1. 2 yr experience, 9 test score, 6 interview score
2. 12 yr experience, 10 test score, 10 interview score.

In [50]:
#load data

hiring = pd.read_csv('/content/drive/MyDrive/WTF-Material_Class B/hiring (1).csv')
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [51]:
#creating a numeric column for experience with map (converting strings to float)

experience_map = {
    'five': 5,
    'two': 2,
    'seven': 7,
    'three': 3,
    'ten': 10,
    'eleven': 11

}
hiring['experience'] = hiring['experience'].map(experience_map)
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [52]:
#calculating experience mean to get a middle number for NaN

hiring['experience'].mean()

np.float64(6.333333333333333)

In [53]:
#filling NaN with experience mean

hiring['experience'].fillna(hiring['experience'].mean(), inplace=True)
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0    6.333333                    8.0                           9      50000
1    6.333333                    8.0                           6      45000
2    5.000000                    6.0                           7      60000
3    2.000000                   10.0                          10      65000
4    7.000000                    9.0                           6      70000
5    3.000000                    7.0                          10      62000
6   10.000000                    NaN                           7      72000
7   11.000000                    7.0                           8      80000

In [54]:
#converting float to integer type

hiring['experience'] = hiring['experience'].round().astype(int)
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [55]:
#calculating test_score(out of 10) median to get a middle number for NaN

hiring['test_score(out of 10)'].median()

8.0

In [56]:
#filling NaN with test_score(out of 10) median

hiring['test_score(out of 10)'].fillna(hiring['test_score(out of 10)'].median(), inplace=True)
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [57]:
#splitting dependent variables from independent variables

indpt_var = hiring.drop('salary($)', axis='columns')
indpt_var

experience  test_score(out of 10)  interview_score(out of 10)
0           6                    8.0                           9
1           6                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [58]:
#creating a dependent variable

dpt_var = hiring['salary($)']
dpt_var

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [69]:
#train model with the independent and dependent variables

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(indpt_var, dpt_var)

LinearRegression()

In [73]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [72]:
reg.intercept_

np.float64(11869.91869918695)

In [71]:
reg.score(indpt_var, dpt_var)

0.4000070238283374

In [63]:
# 2 yr experience, 9 test score, 6 interview score

reg.predict([[2, 9, 6]])

array([47056.91056911])

In [64]:
# 12 yr experience, 10 test score, 10 interview score

reg.predict([[12, 10, 10]])

array([88227.64227642])